name: Linting

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4

            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: '14.x'

            - name: Environment Information
              run: |
                  node --version
                  npm --version

            - name: Linting
              run: |
                  npm ci
                  npm run lint
