name: Run a security audit

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.4.0
            - uses: actions/setup-node@v3
            - run: npm audit
