on: push
name: Security
jobs:
  runaSecurityAudit:
    name: Run a security audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
    - uses: actions/setup-node@v1
    - run: npm audit
